{
  "file_path": "C:\\Users\\hentschel\\git\\mozart_piano\\TiLiA\\Kristian Bezuidenhout - W.A. Mozart_ Fantasie in d (KWV 397).tla",
  "media_path": "C:/Users/hentschel/Nextcloud/Shared/SNF-Projekt Musical Form/Audio/Kristian Bezuidenhout - W.A. Mozart_ Fantasie in d (KWV 397).m4a",
  "media_metadata": {
    "title": "Untitled",
    "notes": "",
    "composer": "",
    "tonality": "",
    "time signature": "",
    "performer": "",
    "performance year": "",
    "arranger": "",
    "composition year": "",
    "recording year": "",
    "form": "",
    "instrumentation": "",
    "genre": "",
    "lyrics": "",
    "media length": 329.305
  },
  "timelines": {
    "1": {
      "is_visible": true,
      "ordinal": 1,
      "height": 40,
      "kind": "SLIDER_TIMELINE",
      "components": {},
      "components_hash": "",
      "hash": ""
    },
    "2": {
      "kind": "BEAT_TIMELINE",
      "beat_pattern": [
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        1,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        1,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        1,
        4,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        1,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2
      ],
      "measure_numbers": [],
      "beats_in_measure": [],
      "measures_to_force_display": [],
      "height": 35,
      "is_visible": true,
      "name": "Measures",
      "ordinal": 2,
      "hash": "e3744a65e66d3b3282df7b77c8269054",
      "components": {},
      "components_hash": "d41d8cd98f00b204e9800998ecf8427e"
    }
  },
  "timelines_hash": "966ec7e23df4bda781ec80209260c389",
  "app_name": "TiLiA",
  "version": "0.5.0"
}